export {
  AGENT_PROTOCOL_VERSION,
  ContentItemSchema,
  CallErrorSchema,
  JSONSchemaObjectSchema,
  AgentToolSchema,
  AgentCapabilitiesSchema,
  AgentMetaSchema,
  AgentRegisterMessageSchema,
  AgentPingMessageSchema,
  AgentPongMessageSchema,
  RegisteredMessageSchema,
  AgentCapabilitiesUpdateMessageSchema,
  AgentCallRequestSchema,
  StreamChunkMessageSchema,
  AgentCallResultSchema,
  OutgoingMessageSchema,
  IncomingMessageSchema,
  parseIncomingMessage,
  validateOutgoingMessage,
  isCallMessage,
  isPingMessage,
  isRegisteredMessage,
  createRegisterMessage,
  createPongMessage,
  createCallResultSuccess,
  createCallResultError,
  createCapabilitiesUpdateMessage,
} from '@helix/shared';

export type {
  ContentItem,
  CallError,
  JSONSchemaObject,
  AgentTool,
  AgentCapabilities,
  AgentMeta,
  RegisterMessage,
  PingMessage,
  PongMessage,
  RegisteredMessage,
  CapabilitiesUpdateMessage,
  StreamChunkMessage,
  CallMessage,
  CallResultSuccess,
  CallResultError,
  CallResult,
  OutgoingMessage,
  IncomingMessage,
} from '@helix/shared';
